spring.application.name=secure-api-server

# Activer tous les détails de santé (pour le dev)
management.endpoint.health.show-details=always

# Exposer les endpoints sur le web
management.endpoints.web.exposure.include=health,info