#Auteur : Athos Cruchet
#Date : 12.11.2025
#Version 1.0

#Rôle : sert de point d'entrée HTTP unique
        # sert le front (front statique)
        # reverse proxy vers l'API (spring boot)

# Upstreams vers les containers du compose (noms = services)
upstream api_up{
    server api:8080
    keepalive 32;
}

upstream front_up{
    server front:80;
    keepalive 32;
}

server {
listen 80; # port d'écoute du serveur Nginx à l'intérieur du container
server_name _; # "_" signifie "tous les noms d'hôtes"


#logs des requêtes HTTP et des erreurs
access_log /var/log/nginx/access.log;
error_log /var/log/nginx/error.log warn;

add_header X-Frame-Options SAMEORIGIN always; #empêche l'intégration dans un iframe externe
add_header X-content-Type-Options nosniff always; #interdit au navigateur de de viner le type

location / {
    proxy_pass http//front_up; #envoie la requête au container "front" (notre nginx statique)
    proxy_http_version 1.1;

    # transmission des en têtes du client (utile pour les logs côtés backend)
    proxy_set_header Host $host;
    proxy_set_header Host X-Real-IP $remote_addr;
    proxy_set_header Host X-Forward-For $proxy_add_x_forwarded_for;

    #connection vide = laisse Nginx gérer keep-alive automatiquement
    proxy_set_header Connection "";
}


location /api/ {

    #redirection vers le container "api" (Spring Boot)
    # /api/user - http://api_up/users
    proxy_pass http://api_up;

    #garde les connexions ouvertes et stables
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Connection "";

    #gestion des lenteurs côté API

    proxy_connect_timeout 5s;       #max 5s pour se connecter à l'API
    proxy_read_timeout 60s;         #max 60s pour lire la réponse

    #autorise le front à appeler L'API

    add_header Access-Control
    add_header Access-Control-Allow-Methods "GET,POST,PUT,PATCH,DELETE,OPTIONS"
    add_header Access-Control-Allow-Headers "Authorization, Content-type";

    #répond imédiatemment aux requêtes OPTIONS
    if ($request_method = OPTIONS) {return 204;}
    }

}
