spring.application.name=secure-api-server

# Activer tous les d�tails de sant� (pour le dev)
management.endpoint.health.show-details=always

# Exposer les endpoints sur le web
management.endpoints.web.exposure.include=health,info